/**
 * Analytics Hub — scheduled report processor.
 *
 * `processAnalyticsReportSchedules()` is called once per campaign-executor tick
 * (like the log-retention / notification-digest sweeps). It finds enabled
 * schedules that are DUE per their frequency + schedule_config_json, generates
 * a report and emails it to recipients_json.
 *
 * Due logic:
 *   • daily   — once per UTC day, at/after schedule_config_json.hour (default 8)
 *   • weekly  — on schedule_config_json.dayOfWeek (0=Sun..6=Sat, default 1/Mon),
 *               at/after .hour, once per that day
 *   • monthly — on schedule_config_json.dayOfMonth (default 1), at/after .hour
 *   • custom  — schedule_config_json.intervalHours since last_run_at
 *
 * NEVER throws — per-schedule failures are recorded in last_error and skipped.
 */
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import {
  generateAnalyticsReport,
  type AnalyticsReportType,
} from "./report-generator.server";
import { sendAnalyticsReportEmail } from "./report-email.server";

type Sb = any;

export interface ScheduleTickResult {
  scanned: number;
  ran: number;
  failed: number;
}

/**
 * Event-driven report kinds: these schedule rows only store the client's
 * email preferences (enabled + recipients) for reports that the WBAH campaign
 * run tick emits when a dialler run actually starts/finishes. They must NEVER
 * be generated by this periodic sweep.
 */
export const EVENT_REPORT_TYPES: ReadonlySet<string> = new Set([
  "wbah_campaign_start",
  "wbah_campaign_end",
]);

export function isDue(schedule: any, now: Date): boolean {
  if (EVENT_REPORT_TYPES.has(String(schedule.report_type))) return false;
  const cfg = (schedule.schedule_config_json ?? {}) as Record<string, any>;
  const hour = Number.isFinite(Number(cfg.hour)) ? Number(cfg.hour) : 8;
  const lastRun = schedule.last_run_at ? new Date(schedule.last_run_at) : null;
  const nowHour = now.getUTCHours();
  const todayKey = now.toISOString().slice(0, 10);
  const lastRunKey = lastRun ? lastRun.toISOString().slice(0, 10) : null;

  switch (schedule.frequency) {
    case "daily":
      if (nowHour < hour) return false;
      return lastRunKey !== todayKey;
    case "weekly": {
      const dow = Number.isFinite(Number(cfg.dayOfWeek)) ? Number(cfg.dayOfWeek) : 1;
      if (now.getUTCDay() !== dow) return false;
      if (nowHour < hour) return false;
      return lastRunKey !== todayKey;
    }
    case "monthly": {
      const dom = Number.isFinite(Number(cfg.dayOfMonth)) ? Number(cfg.dayOfMonth) : 1;
      if (now.getUTCDate() !== dom) return false;
      if (nowHour < hour) return false;
      return lastRunKey !== todayKey;
    }
    case "custom": {
      const intervalHours = Number.isFinite(Number(cfg.intervalHours)) ? Number(cfg.intervalHours) : 24;
      if (!lastRun) return true;
      return now.getTime() - lastRun.getTime() >= intervalHours * 3600_000;
    }
    default:
      return false;
  }
}

export async function processAnalyticsReportSchedules(): Promise<ScheduleTickResult> {
  const result: ScheduleTickResult = { scanned: 0, ran: 0, failed: 0 };
  try {
    const sb = supabaseAdmin as Sb;
    const { data: schedules, error } = await sb
      .from("analytics_report_schedules")
      .select("*")
      .eq("enabled", true)
      .limit(500);
    if (error || !schedules?.length) return result;

    const now = new Date();
    for (const schedule of schedules) {
      result.scanned++;
      try {
        if (!isDue(schedule, now)) continue;

        // Claim the schedule BEFORE generating/sending (compare-and-set on the
        // previous last_run_at) so a failed state write or a concurrent tick
        // can never double-send the same schedule.
        let claim = sb
          .from("analytics_report_schedules")
          .update({ last_run_at: now.toISOString(), updated_at: now.toISOString() })
          .eq("id", schedule.id)
          .eq("enabled", true);
        claim = schedule.last_run_at
          ? claim.eq("last_run_at", schedule.last_run_at)
          : claim.is("last_run_at", null);
        const { data: claimed, error: claimError } = await claim.select("id");
        if (claimError) {
          result.failed++;
          console.warn(
            "[analytics-hub] schedule claim failed (skipping):",
            schedule.id,
            claimError.message,
          );
          continue;
        }
        if (!claimed?.length) continue; // another tick already claimed it

        const filters = (schedule.filters_json ?? {}) as Record<string, any>;
        const recipients: string[] = Array.isArray(schedule.recipients_json)
          ? schedule.recipients_json.map((r: any) => String(r)).filter(Boolean)
          : [];

        const reportId = await generateAnalyticsReport({
          workspaceId: schedule.workspace_id,
          reportType: schedule.report_type as AnalyticsReportType,
          name: schedule.name ?? null,
          dateFilter: filters.dateFilter ?? null,
          dateRangeStart: filters.dateRangeStart ?? null,
          dateRangeEnd: filters.dateRangeEnd ?? null,
          relatedCampaignId: filters.campaignId ?? null,
          relatedAgentId: filters.agentId ?? null,
          relatedWorkflowId: filters.workflowId ?? null,
          generatedBy: "system",
        });

        if (!reportId) {
          // Generation refused or failed (generateAnalyticsReport never throws).
          // Surface it instead of silently marking the run successful.
          throw new Error("report_generation_failed_or_disallowed");
        }
        if (recipients.length > 0) {
          await sendAnalyticsReportEmail(reportId, recipients, {
            actingUserId: schedule.created_by_user_id ?? null,
          });
        }

        const { error: clearError } = await sb
          .from("analytics_report_schedules")
          .update({ last_error: null, updated_at: new Date().toISOString() })
          .eq("id", schedule.id);
        if (clearError) {
          console.warn("[analytics-hub] schedule last_error clear failed:", clearError.message);
        }
        result.ran++;
      } catch (schedErr: any) {
        result.failed++;
        try {
          await sb
            .from("analytics_report_schedules")
            .update({
              last_error: String(schedErr?.message ?? "schedule_error").slice(0, 400),
              updated_at: new Date().toISOString(),
            })
            .eq("id", schedule.id);
        } catch {
          /* ignore */
        }
      }
    }
  } catch (err: any) {
    console.warn("[analytics-hub] schedule sweep failed (non-fatal):", err?.message ?? err);
  }
  return result;
}
