/**
 * Server functions for reading campaign reports. Read-only: reports are
 * generated by lifecycle hooks and SystemMind, never by direct client writes.
 */
import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { resolveActiveWorkspace } from "@/lib/workspace/context.server";
import {
  listCampaignReports,
  getCampaignReport,
  listRecentFailureReports,
} from "./campaign-reports.server";

async function ctxWs(context: any): Promise<{ workspaceId: string; role: string }> {
  const { supabase, workspaceId, userId } = context;
  if (!workspaceId) throw new Error("No active workspace");
  const ws = await resolveActiveWorkspace(supabase, userId);
  return { workspaceId: ws.workspaceId, role: ws.workspaceRole };
}

export const listWorkspaceCampaignReports = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input) =>
    z
      .object({
        campaignId: z.string().uuid().nullish(),
        reportType: z.string().max(40).nullish(),
        limit: z.number().int().min(1).max(200).nullish(),
      })
      .parse(input ?? {}),
  )
  .handler(async ({ data, context }) => {
    const { workspaceId, role } = await ctxWs(context);
    return listCampaignReports(workspaceId, {
      campaignId: data.campaignId ?? null,
      reportType: data.reportType ?? null,
      limit: data.limit ?? 50,
      role,
    });
  });

export const getWorkspaceCampaignReport = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input) => z.object({ id: z.string().uuid() }).parse(input))
  .handler(async ({ data, context }) => {
    const { workspaceId } = await ctxWs(context);
    return getCampaignReport(workspaceId, data.id);
  });

export const listWorkspaceCampaignFailures = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    const { workspaceId } = await ctxWs(context);
    return listRecentFailureReports(workspaceId, 10);
  });
