/**
 * Campaign Reports panel — read-only list of automatic lifecycle reports
 * (activated / run summaries / failures / KPIs) plus a failure banner.
 * Reports are generated by the platform; nothing here mutates campaigns.
 */
import { useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { useQuery } from "@tanstack/react-query";
import {
  listWorkspaceCampaignReports,
  listWorkspaceCampaignFailures,
} from "@/lib/campaign-reports/campaign-reports.functions";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { AlertTriangle, ChevronDown, ChevronRight, FileText, CheckCircle2, XCircle } from "lucide-react";

const FAILURE_TYPES = new Set(["failed", "safety_blocked", "no_eligible_leads", "provider_error", "workflow_error"]);

const TYPE_LABEL: Record<string, string> = {
  activated: "Activated",
  paused: "Paused",
  completed: "Completed",
  cancelled: "Cancelled",
  retried: "Fix Applied",
  kpi_summary: "KPI Summary",
  run_summary: "Run Summary",
  failed: "Failed",
  safety_blocked: "Safety Blocked",
  no_eligible_leads: "No Eligible Leads",
  provider_error: "Provider Error",
  workflow_error: "Workflow Error",
};

function ReportBadge({ type }: { type: string }) {
  const isFailure = FAILURE_TYPES.has(type);
  return (
    <Badge variant={isFailure ? "destructive" : "secondary"} className="text-[10px]">
      {isFailure ? <XCircle className="mr-0.5 h-2.5 w-2.5" /> : <CheckCircle2 className="mr-0.5 h-2.5 w-2.5" />}
      {TYPE_LABEL[type] ?? type}
    </Badge>
  );
}

export function CampaignFailureBanner() {
  const failuresFn = useServerFn(listWorkspaceCampaignFailures);
  const { data } = useQuery({
    queryKey: ["campaign-failure-reports"],
    queryFn: () => failuresFn(),
    staleTime: 60_000,
    throwOnError: false,
  });
  const failures = ((data as any) ?? []) as any[];
  // Only surface failures from the last 48h to avoid stale noise.
  const recent = failures.filter(
    (f) => Date.now() - new Date(f.created_at).getTime() < 48 * 3600 * 1000,
  );
  if (recent.length === 0) return null;
  const top = recent[0];
  return (
    <div className="flex items-start gap-2 rounded-xl border border-red-500/30 bg-red-500/[0.06] px-3 py-2.5">
      <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-red-400" />
      <div className="min-w-0 text-xs">
        <p className="font-medium text-red-300">
          {recent.length === 1 ? "A campaign needs attention" : `${recent.length} campaign issues need attention`}
        </p>
        <p className="mt-0.5 truncate text-muted-foreground">{top.report_summary}</p>
        <p className="mt-0.5 text-[11px] text-muted-foreground">
          See the Reports tab for details — SystemMind can diagnose this and propose a fix for approval.
        </p>
      </div>
    </div>
  );
}

export function CampaignReportsPanel({ campaignId }: { campaignId?: string | null }) {
  const listFn = useServerFn(listWorkspaceCampaignReports);
  const [openId, setOpenId] = useState<string | null>(null);

  const { data, isLoading } = useQuery({
    queryKey: ["campaign-reports", campaignId ?? "all"],
    queryFn: () => listFn({ data: { campaignId: campaignId ?? null, limit: 50 } }),
    staleTime: 30_000,
    throwOnError: false,
  });
  const reports = ((data as any) ?? []) as any[];

  if (isLoading) {
    return <p className="p-4 text-xs text-muted-foreground">Loading reports…</p>;
  }
  if (reports.length === 0) {
    return (
      <div className="rounded-xl border border-white/[0.06] bg-card/60 p-6 text-center">
        <FileText className="mx-auto h-6 w-6 text-muted-foreground/50" />
        <p className="mt-2 text-sm text-muted-foreground">No campaign reports yet.</p>
        <p className="mt-1 text-xs text-muted-foreground/70">
          Reports are generated automatically when campaigns activate, run, complete or hit problems.
        </p>
      </div>
    );
  }

  return (
    <div className="divide-y divide-white/[0.04] rounded-xl border border-white/[0.06] bg-card/60">
      {reports.map((r) => {
        const open = openId === r.id;
        const kpis = (r.kpi_json ?? {}) as Record<string, unknown>;
        const actions = (r.recommended_actions_json ?? []) as Array<{ action: string; detail?: string }>;
        return (
          <div key={r.id}>
            <button
              type="button"
              className="flex w-full items-center justify-between gap-2 px-3 py-2.5 text-left"
              onClick={() => setOpenId(open ? null : r.id)}
            >
              <div className="flex min-w-0 items-center gap-2">
                <ReportBadge type={r.report_type} />
                <p className="truncate text-sm">{r.campaign_name ?? "Campaign"}</p>
                <p className="hidden truncate text-xs text-muted-foreground sm:block">{r.report_summary}</p>
              </div>
              <div className="flex shrink-0 items-center gap-2">
                <p className="text-[11px] text-muted-foreground">{new Date(r.created_at).toLocaleString()}</p>
                {open ? <ChevronDown className="h-3.5 w-3.5" /> : <ChevronRight className="h-3.5 w-3.5" />}
              </div>
            </button>
            {open && (
              <div className="space-y-2 border-t border-white/[0.04] bg-black/10 px-4 py-3 text-xs">
                <p>{r.report_summary}</p>
                {r.failure_reason && (
                  <p className="text-red-300">Reason: {r.failure_reason}{r.failure_stage ? ` (stage: ${r.failure_stage})` : ""}</p>
                )}
                {r.error_message && <p className="text-muted-foreground">Error: {r.error_message}</p>}
                {Object.keys(kpis).length > 0 && (
                  <div className="flex flex-wrap gap-1.5">
                    {Object.entries(kpis).slice(0, 12).map(([k, v]) => (
                      <Badge key={k} variant="outline" className="text-[10px] font-normal">
                        {k.replace(/_/g, " ")}: {typeof v === "object" ? JSON.stringify(v) : String(v)}
                      </Badge>
                    ))}
                  </div>
                )}
                {actions.length > 0 && (
                  <div>
                    <p className="font-medium text-muted-foreground">Recommended actions</p>
                    <ul className="mt-1 list-disc space-y-0.5 pl-4 text-muted-foreground">
                      {actions.map((a, i) => (
                        <li key={i}>{a.action}{a.detail ? ` — ${a.detail}` : ""}</li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}
