// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/AdVideoTemplate.tsx": () => import("../components/mockups/AdVideoTemplate.tsx"),
  "./components/mockups/ui-redesign/CallsPage.tsx": () => import("../components/mockups/ui-redesign/CallsPage.tsx"),
  "./components/mockups/ui-redesign/Dashboard.tsx": () => import("../components/mockups/ui-redesign/Dashboard.tsx"),
  "./components/mockups/ui-redesign/DesignSystem.tsx": () => import("../components/mockups/ui-redesign/DesignSystem.tsx"),
  "./components/mockups/builder/BuilderImproved.tsx": () => import("../components/mockups/builder/BuilderImproved.tsx"),
  "./components/mockups/pages/AnalyticsPage.tsx": () => import("../components/mockups/pages/AnalyticsPage.tsx"),
  "./components/mockups/pages/BillingPage.tsx": () => import("../components/mockups/pages/BillingPage.tsx"),
  "./components/mockups/pages/DataPage.tsx": () => import("../components/mockups/pages/DataPage.tsx"),
  "./components/mockups/pages/TemplatesPage.tsx": () => import("../components/mockups/pages/TemplatesPage.tsx")
};
