/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiVoiceCopilotRouteImport } from './routes/api/voice-copilot'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedTelephonySettingsRouteImport } from './routes/_authenticated/telephony-settings'
import { Route as AuthenticatedTelephonyCallsRouteImport } from './routes/_authenticated/telephony-calls'
import { Route as AuthenticatedQualifiedRouteImport } from './routes/_authenticated/qualified'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedPhoneNumbersRouteImport } from './routes/_authenticated/phone-numbers'
import { Route as AuthenticatedMyAgentsRouteImport } from './routes/_authenticated/my-agents'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedDataRouteImport } from './routes/_authenticated/data'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedCallsRouteImport } from './routes/_authenticated/calls'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedBuilderRouteImport } from './routes/_authenticated/builder'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiWebhookWatiInboundRouteImport } from './routes/api/webhook/wati-inbound'
import { Route as ApiWebhookCustomTelemetryRouteImport } from './routes/api/webhook/custom-telemetry'
import { Route as ApiPublicVoiceWebhookRouteImport } from './routes/api/public/voice-webhook'
import { Route as ApiPublicRetellWebhookRouteImport } from './routes/api/public/retell-webhook'
import { Route as ApiPublicElevenlabsWebhookRouteImport } from './routes/api/public/elevenlabs-webhook'
import { Route as ApiPublicApproveUserRouteImport } from './routes/api/public/approve-user'
import { Route as ApiDashboardLiveCallsSseRouteImport } from './routes/api/dashboard/live-calls-sse'
import { Route as ApiBuilderScriptTemplateRouteImport } from './routes/api/builder/script-template'
import { Route as ApiBuilderScanPdfRouteImport } from './routes/api/builder/scan-pdf'
import { Route as ApiBuilderImportPdfRouteImport } from './routes/api/builder/import-pdf'
import { Route as ApiAdminTestRetellWebhookRouteImport } from './routes/api/admin/test-retell-webhook'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings.integrations'
import { Route as AuthenticatedSettingsCrmRouteImport } from './routes/_authenticated/settings.crm'
import { Route as AuthenticatedSettingsCalendarRouteImport } from './routes/_authenticated/settings.calendar'
import { Route as AuthenticatedAgentsNewRouteImport } from './routes/_authenticated/agents.new'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminUserActivityRouteImport } from './routes/_authenticated/admin.user-activity'
import { Route as AuthenticatedAdminCostEngineRouteImport } from './routes/_authenticated/admin.cost-engine'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiRuntimeAgentIdRouteImport } from './routes/api/runtime/agent.$id'
import { Route as ApiPublicWhatsappWebhookWorkspaceIdRouteImport } from './routes/api/public/whatsapp-webhook.$workspaceId'
import { Route as ApiPublicVoiceWebhookHealthRouteImport } from './routes/api/public/voice-webhook.health'
import { Route as ApiPublicTelephonyStatusRouteImport } from './routes/api/public/telephony/status'
import { Route as ApiPublicTelephonyRecordingRouteImport } from './routes/api/public/telephony/recording'
import { Route as ApiPublicTelephonyInboundRouteImport } from './routes/api/public/telephony/inbound'
import { Route as ApiPublicRetellRescheduleRouteImport } from './routes/api/public/retell/reschedule'
import { Route as ApiPublicRetellEventTypesRouteImport } from './routes/api/public/retell/event-types'
import { Route as ApiPublicRetellCancelRouteImport } from './routes/api/public/retell/cancel'
import { Route as ApiPublicRetellBookRouteImport } from './routes/api/public/retell/book'
import { Route as ApiPublicRetellAvailabilityRouteImport } from './routes/api/public/retell/availability'
import { Route as ApiPublicRetellWebhookHealthRouteImport } from './routes/api/public/retell-webhook.health'
import { Route as ApiPublicRetellWebhookDebugRouteImport } from './routes/api/public/retell-webhook.debug'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHyperstreamRescheduleRouteImport } from './routes/api/public/hyperstream/reschedule'
import { Route as ApiPublicHyperstreamEventTypesRouteImport } from './routes/api/public/hyperstream/event-types'
import { Route as ApiPublicHyperstreamCancelRouteImport } from './routes/api/public/hyperstream/cancel'
import { Route as ApiPublicHyperstreamBookRouteImport } from './routes/api/public/hyperstream/book'
import { Route as ApiPublicHyperstreamAvailabilityRouteImport } from './routes/api/public/hyperstream/availability'
import { Route as ApiPublicFrejunStatusRouteImport } from './routes/api/public/frejun/status'
import { Route as ApiPublicFrejunFlowRouteImport } from './routes/api/public/frejun/flow'
import { Route as ApiPublicCalcomWebhookWorkspaceIdRouteImport } from './routes/api/public/calcom-webhook.$workspaceId'
import { Route as ApiPublicAgentsRegisterRouteImport } from './routes/api/public/agents/register'
import { Route as ApiInternalAgentToolsIdRouteImport } from './routes/api/internal/agent-tools.$id'
import { Route as ApiRuntimeAgentIdExportRouteImport } from './routes/api/runtime/agent.$id.export'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceCopilotRoute = ApiVoiceCopilotRouteImport.update({
  id: '/api/voice-copilot',
  path: '/api/voice-copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTelephonySettingsRoute =
  AuthenticatedTelephonySettingsRouteImport.update({
    id: '/telephony-settings',
    path: '/telephony-settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTelephonyCallsRoute =
  AuthenticatedTelephonyCallsRouteImport.update({
    id: '/telephony-calls',
    path: '/telephony-calls',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQualifiedRoute = AuthenticatedQualifiedRouteImport.update({
  id: '/qualified',
  path: '/qualified',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPhoneNumbersRoute =
  AuthenticatedPhoneNumbersRouteImport.update({
    id: '/phone-numbers',
    path: '/phone-numbers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyAgentsRoute = AuthenticatedMyAgentsRouteImport.update({
  id: '/my-agents',
  path: '/my-agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDataRoute = AuthenticatedDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCallsRoute = AuthenticatedCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBuilderRoute = AuthenticatedBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookWatiInboundRoute = ApiWebhookWatiInboundRouteImport.update({
  id: '/api/webhook/wati-inbound',
  path: '/api/webhook/wati-inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookCustomTelemetryRoute =
  ApiWebhookCustomTelemetryRouteImport.update({
    id: '/api/webhook/custom-telemetry',
    path: '/api/webhook/custom-telemetry',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVoiceWebhookRoute = ApiPublicVoiceWebhookRouteImport.update({
  id: '/api/public/voice-webhook',
  path: '/api/public/voice-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRetellWebhookRoute = ApiPublicRetellWebhookRouteImport.update({
  id: '/api/public/retell-webhook',
  path: '/api/public/retell-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicElevenlabsWebhookRoute =
  ApiPublicElevenlabsWebhookRouteImport.update({
    id: '/api/public/elevenlabs-webhook',
    path: '/api/public/elevenlabs-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicApproveUserRoute = ApiPublicApproveUserRouteImport.update({
  id: '/api/public/approve-user',
  path: '/api/public/approve-user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardLiveCallsSseRoute =
  ApiDashboardLiveCallsSseRouteImport.update({
    id: '/api/dashboard/live-calls-sse',
    path: '/api/dashboard/live-calls-sse',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBuilderScriptTemplateRoute =
  ApiBuilderScriptTemplateRouteImport.update({
    id: '/api/builder/script-template',
    path: '/api/builder/script-template',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBuilderScanPdfRoute = ApiBuilderScanPdfRouteImport.update({
  id: '/api/builder/scan-pdf',
  path: '/api/builder/scan-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuilderImportPdfRoute = ApiBuilderImportPdfRouteImport.update({
  id: '/api/builder/import-pdf',
  path: '/api/builder/import-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTestRetellWebhookRoute =
  ApiAdminTestRetellWebhookRouteImport.update({
    id: '/api/admin/test-retell-webhook',
    path: '/api/admin/test-retell-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/settings/integrations',
    path: '/settings/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsCrmRoute =
  AuthenticatedSettingsCrmRouteImport.update({
    id: '/settings/crm',
    path: '/settings/crm',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsCalendarRoute =
  AuthenticatedSettingsCalendarRouteImport.update({
    id: '/settings/calendar',
    path: '/settings/calendar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgentsNewRoute = AuthenticatedAgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUserActivityRoute =
  AuthenticatedAdminUserActivityRouteImport.update({
    id: '/user-activity',
    path: '/user-activity',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCostEngineRoute =
  AuthenticatedAdminCostEngineRouteImport.update({
    id: '/cost-engine',
    path: '/cost-engine',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeAgentIdRoute = ApiRuntimeAgentIdRouteImport.update({
  id: '/api/runtime/agent/$id',
  path: '/api/runtime/agent/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookWorkspaceIdRoute =
  ApiPublicWhatsappWebhookWorkspaceIdRouteImport.update({
    id: '/api/public/whatsapp-webhook/$workspaceId',
    path: '/api/public/whatsapp-webhook/$workspaceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVoiceWebhookHealthRoute =
  ApiPublicVoiceWebhookHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => ApiPublicVoiceWebhookRoute,
  } as any)
const ApiPublicTelephonyStatusRoute =
  ApiPublicTelephonyStatusRouteImport.update({
    id: '/api/public/telephony/status',
    path: '/api/public/telephony/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelephonyRecordingRoute =
  ApiPublicTelephonyRecordingRouteImport.update({
    id: '/api/public/telephony/recording',
    path: '/api/public/telephony/recording',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelephonyInboundRoute =
  ApiPublicTelephonyInboundRouteImport.update({
    id: '/api/public/telephony/inbound',
    path: '/api/public/telephony/inbound',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRetellRescheduleRoute =
  ApiPublicRetellRescheduleRouteImport.update({
    id: '/api/public/retell/reschedule',
    path: '/api/public/retell/reschedule',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRetellEventTypesRoute =
  ApiPublicRetellEventTypesRouteImport.update({
    id: '/api/public/retell/event-types',
    path: '/api/public/retell/event-types',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRetellCancelRoute = ApiPublicRetellCancelRouteImport.update({
  id: '/api/public/retell/cancel',
  path: '/api/public/retell/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRetellBookRoute = ApiPublicRetellBookRouteImport.update({
  id: '/api/public/retell/book',
  path: '/api/public/retell/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRetellAvailabilityRoute =
  ApiPublicRetellAvailabilityRouteImport.update({
    id: '/api/public/retell/availability',
    path: '/api/public/retell/availability',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRetellWebhookHealthRoute =
  ApiPublicRetellWebhookHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => ApiPublicRetellWebhookRoute,
  } as any)
const ApiPublicRetellWebhookDebugRoute =
  ApiPublicRetellWebhookDebugRouteImport.update({
    id: '/debug',
    path: '/debug',
    getParentRoute: () => ApiPublicRetellWebhookRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHyperstreamRescheduleRoute =
  ApiPublicHyperstreamRescheduleRouteImport.update({
    id: '/api/public/hyperstream/reschedule',
    path: '/api/public/hyperstream/reschedule',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHyperstreamEventTypesRoute =
  ApiPublicHyperstreamEventTypesRouteImport.update({
    id: '/api/public/hyperstream/event-types',
    path: '/api/public/hyperstream/event-types',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHyperstreamCancelRoute =
  ApiPublicHyperstreamCancelRouteImport.update({
    id: '/api/public/hyperstream/cancel',
    path: '/api/public/hyperstream/cancel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHyperstreamBookRoute =
  ApiPublicHyperstreamBookRouteImport.update({
    id: '/api/public/hyperstream/book',
    path: '/api/public/hyperstream/book',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHyperstreamAvailabilityRoute =
  ApiPublicHyperstreamAvailabilityRouteImport.update({
    id: '/api/public/hyperstream/availability',
    path: '/api/public/hyperstream/availability',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFrejunStatusRoute = ApiPublicFrejunStatusRouteImport.update({
  id: '/api/public/frejun/status',
  path: '/api/public/frejun/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFrejunFlowRoute = ApiPublicFrejunFlowRouteImport.update({
  id: '/api/public/frejun/flow',
  path: '/api/public/frejun/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCalcomWebhookWorkspaceIdRoute =
  ApiPublicCalcomWebhookWorkspaceIdRouteImport.update({
    id: '/api/public/calcom-webhook/$workspaceId',
    path: '/api/public/calcom-webhook/$workspaceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentsRegisterRoute = ApiPublicAgentsRegisterRouteImport.update({
  id: '/api/public/agents/register',
  path: '/api/public/agents/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalAgentToolsIdRoute = ApiInternalAgentToolsIdRouteImport.update({
  id: '/api/internal/agent-tools/$id',
  path: '/api/internal/agent-tools/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeAgentIdExportRoute = ApiRuntimeAgentIdExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ApiRuntimeAgentIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/builder': typeof AuthenticatedBuilderRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/data': typeof AuthenticatedDataRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/my-agents': typeof AuthenticatedMyAgentsRoute
  '/phone-numbers': typeof AuthenticatedPhoneNumbersRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/qualified': typeof AuthenticatedQualifiedRoute
  '/telephony-calls': typeof AuthenticatedTelephonyCallsRoute
  '/telephony-settings': typeof AuthenticatedTelephonySettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/api/voice-copilot': typeof ApiVoiceCopilotRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/cost-engine': typeof AuthenticatedAdminCostEngineRoute
  '/admin/user-activity': typeof AuthenticatedAdminUserActivityRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/agents/new': typeof AuthenticatedAgentsNewRoute
  '/settings/calendar': typeof AuthenticatedSettingsCalendarRoute
  '/settings/crm': typeof AuthenticatedSettingsCrmRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/api/admin/test-retell-webhook': typeof ApiAdminTestRetellWebhookRoute
  '/api/builder/import-pdf': typeof ApiBuilderImportPdfRoute
  '/api/builder/scan-pdf': typeof ApiBuilderScanPdfRoute
  '/api/builder/script-template': typeof ApiBuilderScriptTemplateRoute
  '/api/dashboard/live-calls-sse': typeof ApiDashboardLiveCallsSseRoute
  '/api/public/approve-user': typeof ApiPublicApproveUserRoute
  '/api/public/elevenlabs-webhook': typeof ApiPublicElevenlabsWebhookRoute
  '/api/public/retell-webhook': typeof ApiPublicRetellWebhookRouteWithChildren
  '/api/public/voice-webhook': typeof ApiPublicVoiceWebhookRouteWithChildren
  '/api/webhook/custom-telemetry': typeof ApiWebhookCustomTelemetryRoute
  '/api/webhook/wati-inbound': typeof ApiWebhookWatiInboundRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/internal/agent-tools/$id': typeof ApiInternalAgentToolsIdRoute
  '/api/public/agents/register': typeof ApiPublicAgentsRegisterRoute
  '/api/public/calcom-webhook/$workspaceId': typeof ApiPublicCalcomWebhookWorkspaceIdRoute
  '/api/public/frejun/flow': typeof ApiPublicFrejunFlowRoute
  '/api/public/frejun/status': typeof ApiPublicFrejunStatusRoute
  '/api/public/hyperstream/availability': typeof ApiPublicHyperstreamAvailabilityRoute
  '/api/public/hyperstream/book': typeof ApiPublicHyperstreamBookRoute
  '/api/public/hyperstream/cancel': typeof ApiPublicHyperstreamCancelRoute
  '/api/public/hyperstream/event-types': typeof ApiPublicHyperstreamEventTypesRoute
  '/api/public/hyperstream/reschedule': typeof ApiPublicHyperstreamRescheduleRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/retell-webhook/debug': typeof ApiPublicRetellWebhookDebugRoute
  '/api/public/retell-webhook/health': typeof ApiPublicRetellWebhookHealthRoute
  '/api/public/retell/availability': typeof ApiPublicRetellAvailabilityRoute
  '/api/public/retell/book': typeof ApiPublicRetellBookRoute
  '/api/public/retell/cancel': typeof ApiPublicRetellCancelRoute
  '/api/public/retell/event-types': typeof ApiPublicRetellEventTypesRoute
  '/api/public/retell/reschedule': typeof ApiPublicRetellRescheduleRoute
  '/api/public/telephony/inbound': typeof ApiPublicTelephonyInboundRoute
  '/api/public/telephony/recording': typeof ApiPublicTelephonyRecordingRoute
  '/api/public/telephony/status': typeof ApiPublicTelephonyStatusRoute
  '/api/public/voice-webhook/health': typeof ApiPublicVoiceWebhookHealthRoute
  '/api/public/whatsapp-webhook/$workspaceId': typeof ApiPublicWhatsappWebhookWorkspaceIdRoute
  '/api/runtime/agent/$id': typeof ApiRuntimeAgentIdRouteWithChildren
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/runtime/agent/$id/export': typeof ApiRuntimeAgentIdExportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/builder': typeof AuthenticatedBuilderRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/data': typeof AuthenticatedDataRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/my-agents': typeof AuthenticatedMyAgentsRoute
  '/phone-numbers': typeof AuthenticatedPhoneNumbersRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/qualified': typeof AuthenticatedQualifiedRoute
  '/telephony-calls': typeof AuthenticatedTelephonyCallsRoute
  '/telephony-settings': typeof AuthenticatedTelephonySettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/api/voice-copilot': typeof ApiVoiceCopilotRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/cost-engine': typeof AuthenticatedAdminCostEngineRoute
  '/admin/user-activity': typeof AuthenticatedAdminUserActivityRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/agents/new': typeof AuthenticatedAgentsNewRoute
  '/settings/calendar': typeof AuthenticatedSettingsCalendarRoute
  '/settings/crm': typeof AuthenticatedSettingsCrmRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/api/admin/test-retell-webhook': typeof ApiAdminTestRetellWebhookRoute
  '/api/builder/import-pdf': typeof ApiBuilderImportPdfRoute
  '/api/builder/scan-pdf': typeof ApiBuilderScanPdfRoute
  '/api/builder/script-template': typeof ApiBuilderScriptTemplateRoute
  '/api/dashboard/live-calls-sse': typeof ApiDashboardLiveCallsSseRoute
  '/api/public/approve-user': typeof ApiPublicApproveUserRoute
  '/api/public/elevenlabs-webhook': typeof ApiPublicElevenlabsWebhookRoute
  '/api/public/retell-webhook': typeof ApiPublicRetellWebhookRouteWithChildren
  '/api/public/voice-webhook': typeof ApiPublicVoiceWebhookRouteWithChildren
  '/api/webhook/custom-telemetry': typeof ApiWebhookCustomTelemetryRoute
  '/api/webhook/wati-inbound': typeof ApiWebhookWatiInboundRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/internal/agent-tools/$id': typeof ApiInternalAgentToolsIdRoute
  '/api/public/agents/register': typeof ApiPublicAgentsRegisterRoute
  '/api/public/calcom-webhook/$workspaceId': typeof ApiPublicCalcomWebhookWorkspaceIdRoute
  '/api/public/frejun/flow': typeof ApiPublicFrejunFlowRoute
  '/api/public/frejun/status': typeof ApiPublicFrejunStatusRoute
  '/api/public/hyperstream/availability': typeof ApiPublicHyperstreamAvailabilityRoute
  '/api/public/hyperstream/book': typeof ApiPublicHyperstreamBookRoute
  '/api/public/hyperstream/cancel': typeof ApiPublicHyperstreamCancelRoute
  '/api/public/hyperstream/event-types': typeof ApiPublicHyperstreamEventTypesRoute
  '/api/public/hyperstream/reschedule': typeof ApiPublicHyperstreamRescheduleRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/retell-webhook/debug': typeof ApiPublicRetellWebhookDebugRoute
  '/api/public/retell-webhook/health': typeof ApiPublicRetellWebhookHealthRoute
  '/api/public/retell/availability': typeof ApiPublicRetellAvailabilityRoute
  '/api/public/retell/book': typeof ApiPublicRetellBookRoute
  '/api/public/retell/cancel': typeof ApiPublicRetellCancelRoute
  '/api/public/retell/event-types': typeof ApiPublicRetellEventTypesRoute
  '/api/public/retell/reschedule': typeof ApiPublicRetellRescheduleRoute
  '/api/public/telephony/inbound': typeof ApiPublicTelephonyInboundRoute
  '/api/public/telephony/recording': typeof ApiPublicTelephonyRecordingRoute
  '/api/public/telephony/status': typeof ApiPublicTelephonyStatusRoute
  '/api/public/voice-webhook/health': typeof ApiPublicVoiceWebhookHealthRoute
  '/api/public/whatsapp-webhook/$workspaceId': typeof ApiPublicWhatsappWebhookWorkspaceIdRoute
  '/api/runtime/agent/$id': typeof ApiRuntimeAgentIdRouteWithChildren
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/runtime/agent/$id/export': typeof ApiRuntimeAgentIdExportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/builder': typeof AuthenticatedBuilderRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/calls': typeof AuthenticatedCallsRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/data': typeof AuthenticatedDataRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/my-agents': typeof AuthenticatedMyAgentsRoute
  '/_authenticated/phone-numbers': typeof AuthenticatedPhoneNumbersRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/qualified': typeof AuthenticatedQualifiedRoute
  '/_authenticated/telephony-calls': typeof AuthenticatedTelephonyCallsRoute
  '/_authenticated/telephony-settings': typeof AuthenticatedTelephonySettingsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/api/voice-copilot': typeof ApiVoiceCopilotRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_authenticated/admin/cost-engine': typeof AuthenticatedAdminCostEngineRoute
  '/_authenticated/admin/user-activity': typeof AuthenticatedAdminUserActivityRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/agents/new': typeof AuthenticatedAgentsNewRoute
  '/_authenticated/settings/calendar': typeof AuthenticatedSettingsCalendarRoute
  '/_authenticated/settings/crm': typeof AuthenticatedSettingsCrmRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/api/admin/test-retell-webhook': typeof ApiAdminTestRetellWebhookRoute
  '/api/builder/import-pdf': typeof ApiBuilderImportPdfRoute
  '/api/builder/scan-pdf': typeof ApiBuilderScanPdfRoute
  '/api/builder/script-template': typeof ApiBuilderScriptTemplateRoute
  '/api/dashboard/live-calls-sse': typeof ApiDashboardLiveCallsSseRoute
  '/api/public/approve-user': typeof ApiPublicApproveUserRoute
  '/api/public/elevenlabs-webhook': typeof ApiPublicElevenlabsWebhookRoute
  '/api/public/retell-webhook': typeof ApiPublicRetellWebhookRouteWithChildren
  '/api/public/voice-webhook': typeof ApiPublicVoiceWebhookRouteWithChildren
  '/api/webhook/custom-telemetry': typeof ApiWebhookCustomTelemetryRoute
  '/api/webhook/wati-inbound': typeof ApiWebhookWatiInboundRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/internal/agent-tools/$id': typeof ApiInternalAgentToolsIdRoute
  '/api/public/agents/register': typeof ApiPublicAgentsRegisterRoute
  '/api/public/calcom-webhook/$workspaceId': typeof ApiPublicCalcomWebhookWorkspaceIdRoute
  '/api/public/frejun/flow': typeof ApiPublicFrejunFlowRoute
  '/api/public/frejun/status': typeof ApiPublicFrejunStatusRoute
  '/api/public/hyperstream/availability': typeof ApiPublicHyperstreamAvailabilityRoute
  '/api/public/hyperstream/book': typeof ApiPublicHyperstreamBookRoute
  '/api/public/hyperstream/cancel': typeof ApiPublicHyperstreamCancelRoute
  '/api/public/hyperstream/event-types': typeof ApiPublicHyperstreamEventTypesRoute
  '/api/public/hyperstream/reschedule': typeof ApiPublicHyperstreamRescheduleRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/retell-webhook/debug': typeof ApiPublicRetellWebhookDebugRoute
  '/api/public/retell-webhook/health': typeof ApiPublicRetellWebhookHealthRoute
  '/api/public/retell/availability': typeof ApiPublicRetellAvailabilityRoute
  '/api/public/retell/book': typeof ApiPublicRetellBookRoute
  '/api/public/retell/cancel': typeof ApiPublicRetellCancelRoute
  '/api/public/retell/event-types': typeof ApiPublicRetellEventTypesRoute
  '/api/public/retell/reschedule': typeof ApiPublicRetellRescheduleRoute
  '/api/public/telephony/inbound': typeof ApiPublicTelephonyInboundRoute
  '/api/public/telephony/recording': typeof ApiPublicTelephonyRecordingRoute
  '/api/public/telephony/status': typeof ApiPublicTelephonyStatusRoute
  '/api/public/voice-webhook/health': typeof ApiPublicVoiceWebhookHealthRoute
  '/api/public/whatsapp-webhook/$workspaceId': typeof ApiPublicWhatsappWebhookWorkspaceIdRoute
  '/api/runtime/agent/$id': typeof ApiRuntimeAgentIdRouteWithChildren
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/runtime/agent/$id/export': typeof ApiRuntimeAgentIdExportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/unsubscribe'
    | '/admin'
    | '/analytics'
    | '/billing'
    | '/builder'
    | '/calendar'
    | '/calls'
    | '/campaigns'
    | '/contacts'
    | '/dashboard'
    | '/data'
    | '/leads'
    | '/my-agents'
    | '/phone-numbers'
    | '/pipeline'
    | '/qualified'
    | '/telephony-calls'
    | '/telephony-settings'
    | '/templates'
    | '/whatsapp'
    | '/api/voice-copilot'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/admin/cost-engine'
    | '/admin/user-activity'
    | '/admin/users'
    | '/agents/new'
    | '/settings/calendar'
    | '/settings/crm'
    | '/settings/integrations'
    | '/api/admin/test-retell-webhook'
    | '/api/builder/import-pdf'
    | '/api/builder/scan-pdf'
    | '/api/builder/script-template'
    | '/api/dashboard/live-calls-sse'
    | '/api/public/approve-user'
    | '/api/public/elevenlabs-webhook'
    | '/api/public/retell-webhook'
    | '/api/public/voice-webhook'
    | '/api/webhook/custom-telemetry'
    | '/api/webhook/wati-inbound'
    | '/lovable/email/suppression'
    | '/admin/'
    | '/api/internal/agent-tools/$id'
    | '/api/public/agents/register'
    | '/api/public/calcom-webhook/$workspaceId'
    | '/api/public/frejun/flow'
    | '/api/public/frejun/status'
    | '/api/public/hyperstream/availability'
    | '/api/public/hyperstream/book'
    | '/api/public/hyperstream/cancel'
    | '/api/public/hyperstream/event-types'
    | '/api/public/hyperstream/reschedule'
    | '/api/public/payments/webhook'
    | '/api/public/retell-webhook/debug'
    | '/api/public/retell-webhook/health'
    | '/api/public/retell/availability'
    | '/api/public/retell/book'
    | '/api/public/retell/cancel'
    | '/api/public/retell/event-types'
    | '/api/public/retell/reschedule'
    | '/api/public/telephony/inbound'
    | '/api/public/telephony/recording'
    | '/api/public/telephony/status'
    | '/api/public/voice-webhook/health'
    | '/api/public/whatsapp-webhook/$workspaceId'
    | '/api/runtime/agent/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/runtime/agent/$id/export'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/unsubscribe'
    | '/analytics'
    | '/billing'
    | '/builder'
    | '/calendar'
    | '/calls'
    | '/campaigns'
    | '/contacts'
    | '/dashboard'
    | '/data'
    | '/leads'
    | '/my-agents'
    | '/phone-numbers'
    | '/pipeline'
    | '/qualified'
    | '/telephony-calls'
    | '/telephony-settings'
    | '/templates'
    | '/whatsapp'
    | '/api/voice-copilot'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/admin/cost-engine'
    | '/admin/user-activity'
    | '/admin/users'
    | '/agents/new'
    | '/settings/calendar'
    | '/settings/crm'
    | '/settings/integrations'
    | '/api/admin/test-retell-webhook'
    | '/api/builder/import-pdf'
    | '/api/builder/scan-pdf'
    | '/api/builder/script-template'
    | '/api/dashboard/live-calls-sse'
    | '/api/public/approve-user'
    | '/api/public/elevenlabs-webhook'
    | '/api/public/retell-webhook'
    | '/api/public/voice-webhook'
    | '/api/webhook/custom-telemetry'
    | '/api/webhook/wati-inbound'
    | '/lovable/email/suppression'
    | '/admin'
    | '/api/internal/agent-tools/$id'
    | '/api/public/agents/register'
    | '/api/public/calcom-webhook/$workspaceId'
    | '/api/public/frejun/flow'
    | '/api/public/frejun/status'
    | '/api/public/hyperstream/availability'
    | '/api/public/hyperstream/book'
    | '/api/public/hyperstream/cancel'
    | '/api/public/hyperstream/event-types'
    | '/api/public/hyperstream/reschedule'
    | '/api/public/payments/webhook'
    | '/api/public/retell-webhook/debug'
    | '/api/public/retell-webhook/health'
    | '/api/public/retell/availability'
    | '/api/public/retell/book'
    | '/api/public/retell/cancel'
    | '/api/public/retell/event-types'
    | '/api/public/retell/reschedule'
    | '/api/public/telephony/inbound'
    | '/api/public/telephony/recording'
    | '/api/public/telephony/status'
    | '/api/public/voice-webhook/health'
    | '/api/public/whatsapp-webhook/$workspaceId'
    | '/api/runtime/agent/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/runtime/agent/$id/export'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/unsubscribe'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/billing'
    | '/_authenticated/builder'
    | '/_authenticated/calendar'
    | '/_authenticated/calls'
    | '/_authenticated/campaigns'
    | '/_authenticated/contacts'
    | '/_authenticated/dashboard'
    | '/_authenticated/data'
    | '/_authenticated/leads'
    | '/_authenticated/my-agents'
    | '/_authenticated/phone-numbers'
    | '/_authenticated/pipeline'
    | '/_authenticated/qualified'
    | '/_authenticated/telephony-calls'
    | '/_authenticated/telephony-settings'
    | '/_authenticated/templates'
    | '/_authenticated/whatsapp'
    | '/api/voice-copilot'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/_authenticated/admin/cost-engine'
    | '/_authenticated/admin/user-activity'
    | '/_authenticated/admin/users'
    | '/_authenticated/agents/new'
    | '/_authenticated/settings/calendar'
    | '/_authenticated/settings/crm'
    | '/_authenticated/settings/integrations'
    | '/api/admin/test-retell-webhook'
    | '/api/builder/import-pdf'
    | '/api/builder/scan-pdf'
    | '/api/builder/script-template'
    | '/api/dashboard/live-calls-sse'
    | '/api/public/approve-user'
    | '/api/public/elevenlabs-webhook'
    | '/api/public/retell-webhook'
    | '/api/public/voice-webhook'
    | '/api/webhook/custom-telemetry'
    | '/api/webhook/wati-inbound'
    | '/lovable/email/suppression'
    | '/_authenticated/admin/'
    | '/api/internal/agent-tools/$id'
    | '/api/public/agents/register'
    | '/api/public/calcom-webhook/$workspaceId'
    | '/api/public/frejun/flow'
    | '/api/public/frejun/status'
    | '/api/public/hyperstream/availability'
    | '/api/public/hyperstream/book'
    | '/api/public/hyperstream/cancel'
    | '/api/public/hyperstream/event-types'
    | '/api/public/hyperstream/reschedule'
    | '/api/public/payments/webhook'
    | '/api/public/retell-webhook/debug'
    | '/api/public/retell-webhook/health'
    | '/api/public/retell/availability'
    | '/api/public/retell/book'
    | '/api/public/retell/cancel'
    | '/api/public/retell/event-types'
    | '/api/public/retell/reschedule'
    | '/api/public/telephony/inbound'
    | '/api/public/telephony/recording'
    | '/api/public/telephony/status'
    | '/api/public/voice-webhook/health'
    | '/api/public/whatsapp-webhook/$workspaceId'
    | '/api/runtime/agent/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/runtime/agent/$id/export'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ApiVoiceCopilotRoute: typeof ApiVoiceCopilotRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiAdminTestRetellWebhookRoute: typeof ApiAdminTestRetellWebhookRoute
  ApiBuilderImportPdfRoute: typeof ApiBuilderImportPdfRoute
  ApiBuilderScanPdfRoute: typeof ApiBuilderScanPdfRoute
  ApiBuilderScriptTemplateRoute: typeof ApiBuilderScriptTemplateRoute
  ApiDashboardLiveCallsSseRoute: typeof ApiDashboardLiveCallsSseRoute
  ApiPublicApproveUserRoute: typeof ApiPublicApproveUserRoute
  ApiPublicElevenlabsWebhookRoute: typeof ApiPublicElevenlabsWebhookRoute
  ApiPublicRetellWebhookRoute: typeof ApiPublicRetellWebhookRouteWithChildren
  ApiPublicVoiceWebhookRoute: typeof ApiPublicVoiceWebhookRouteWithChildren
  ApiWebhookCustomTelemetryRoute: typeof ApiWebhookCustomTelemetryRoute
  ApiWebhookWatiInboundRoute: typeof ApiWebhookWatiInboundRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiInternalAgentToolsIdRoute: typeof ApiInternalAgentToolsIdRoute
  ApiPublicAgentsRegisterRoute: typeof ApiPublicAgentsRegisterRoute
  ApiPublicCalcomWebhookWorkspaceIdRoute: typeof ApiPublicCalcomWebhookWorkspaceIdRoute
  ApiPublicFrejunFlowRoute: typeof ApiPublicFrejunFlowRoute
  ApiPublicFrejunStatusRoute: typeof ApiPublicFrejunStatusRoute
  ApiPublicHyperstreamAvailabilityRoute: typeof ApiPublicHyperstreamAvailabilityRoute
  ApiPublicHyperstreamBookRoute: typeof ApiPublicHyperstreamBookRoute
  ApiPublicHyperstreamCancelRoute: typeof ApiPublicHyperstreamCancelRoute
  ApiPublicHyperstreamEventTypesRoute: typeof ApiPublicHyperstreamEventTypesRoute
  ApiPublicHyperstreamRescheduleRoute: typeof ApiPublicHyperstreamRescheduleRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicRetellAvailabilityRoute: typeof ApiPublicRetellAvailabilityRoute
  ApiPublicRetellBookRoute: typeof ApiPublicRetellBookRoute
  ApiPublicRetellCancelRoute: typeof ApiPublicRetellCancelRoute
  ApiPublicRetellEventTypesRoute: typeof ApiPublicRetellEventTypesRoute
  ApiPublicRetellRescheduleRoute: typeof ApiPublicRetellRescheduleRoute
  ApiPublicTelephonyInboundRoute: typeof ApiPublicTelephonyInboundRoute
  ApiPublicTelephonyRecordingRoute: typeof ApiPublicTelephonyRecordingRoute
  ApiPublicTelephonyStatusRoute: typeof ApiPublicTelephonyStatusRoute
  ApiPublicWhatsappWebhookWorkspaceIdRoute: typeof ApiPublicWhatsappWebhookWorkspaceIdRoute
  ApiRuntimeAgentIdRoute: typeof ApiRuntimeAgentIdRouteWithChildren
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice-copilot': {
      id: '/api/voice-copilot'
      path: '/api/voice-copilot'
      fullPath: '/api/voice-copilot'
      preLoaderRoute: typeof ApiVoiceCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/telephony-settings': {
      id: '/_authenticated/telephony-settings'
      path: '/telephony-settings'
      fullPath: '/telephony-settings'
      preLoaderRoute: typeof AuthenticatedTelephonySettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/telephony-calls': {
      id: '/_authenticated/telephony-calls'
      path: '/telephony-calls'
      fullPath: '/telephony-calls'
      preLoaderRoute: typeof AuthenticatedTelephonyCallsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qualified': {
      id: '/_authenticated/qualified'
      path: '/qualified'
      fullPath: '/qualified'
      preLoaderRoute: typeof AuthenticatedQualifiedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/phone-numbers': {
      id: '/_authenticated/phone-numbers'
      path: '/phone-numbers'
      fullPath: '/phone-numbers'
      preLoaderRoute: typeof AuthenticatedPhoneNumbersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-agents': {
      id: '/_authenticated/my-agents'
      path: '/my-agents'
      fullPath: '/my-agents'
      preLoaderRoute: typeof AuthenticatedMyAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data': {
      id: '/_authenticated/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof AuthenticatedDataRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calls': {
      id: '/_authenticated/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AuthenticatedCallsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/builder': {
      id: '/_authenticated/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof AuthenticatedBuilderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/wati-inbound': {
      id: '/api/webhook/wati-inbound'
      path: '/api/webhook/wati-inbound'
      fullPath: '/api/webhook/wati-inbound'
      preLoaderRoute: typeof ApiWebhookWatiInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/custom-telemetry': {
      id: '/api/webhook/custom-telemetry'
      path: '/api/webhook/custom-telemetry'
      fullPath: '/api/webhook/custom-telemetry'
      preLoaderRoute: typeof ApiWebhookCustomTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/voice-webhook': {
      id: '/api/public/voice-webhook'
      path: '/api/public/voice-webhook'
      fullPath: '/api/public/voice-webhook'
      preLoaderRoute: typeof ApiPublicVoiceWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/retell-webhook': {
      id: '/api/public/retell-webhook'
      path: '/api/public/retell-webhook'
      fullPath: '/api/public/retell-webhook'
      preLoaderRoute: typeof ApiPublicRetellWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/elevenlabs-webhook': {
      id: '/api/public/elevenlabs-webhook'
      path: '/api/public/elevenlabs-webhook'
      fullPath: '/api/public/elevenlabs-webhook'
      preLoaderRoute: typeof ApiPublicElevenlabsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/approve-user': {
      id: '/api/public/approve-user'
      path: '/api/public/approve-user'
      fullPath: '/api/public/approve-user'
      preLoaderRoute: typeof ApiPublicApproveUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/live-calls-sse': {
      id: '/api/dashboard/live-calls-sse'
      path: '/api/dashboard/live-calls-sse'
      fullPath: '/api/dashboard/live-calls-sse'
      preLoaderRoute: typeof ApiDashboardLiveCallsSseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builder/script-template': {
      id: '/api/builder/script-template'
      path: '/api/builder/script-template'
      fullPath: '/api/builder/script-template'
      preLoaderRoute: typeof ApiBuilderScriptTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builder/scan-pdf': {
      id: '/api/builder/scan-pdf'
      path: '/api/builder/scan-pdf'
      fullPath: '/api/builder/scan-pdf'
      preLoaderRoute: typeof ApiBuilderScanPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builder/import-pdf': {
      id: '/api/builder/import-pdf'
      path: '/api/builder/import-pdf'
      fullPath: '/api/builder/import-pdf'
      preLoaderRoute: typeof ApiBuilderImportPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/test-retell-webhook': {
      id: '/api/admin/test-retell-webhook'
      path: '/api/admin/test-retell-webhook'
      fullPath: '/api/admin/test-retell-webhook'
      preLoaderRoute: typeof ApiAdminTestRetellWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/crm': {
      id: '/_authenticated/settings/crm'
      path: '/settings/crm'
      fullPath: '/settings/crm'
      preLoaderRoute: typeof AuthenticatedSettingsCrmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/calendar': {
      id: '/_authenticated/settings/calendar'
      path: '/settings/calendar'
      fullPath: '/settings/calendar'
      preLoaderRoute: typeof AuthenticatedSettingsCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents/new': {
      id: '/_authenticated/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AuthenticatedAgentsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/user-activity': {
      id: '/_authenticated/admin/user-activity'
      path: '/user-activity'
      fullPath: '/admin/user-activity'
      preLoaderRoute: typeof AuthenticatedAdminUserActivityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cost-engine': {
      id: '/_authenticated/admin/cost-engine'
      path: '/cost-engine'
      fullPath: '/admin/cost-engine'
      preLoaderRoute: typeof AuthenticatedAdminCostEngineRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime/agent/$id': {
      id: '/api/runtime/agent/$id'
      path: '/api/runtime/agent/$id'
      fullPath: '/api/runtime/agent/$id'
      preLoaderRoute: typeof ApiRuntimeAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp-webhook/$workspaceId': {
      id: '/api/public/whatsapp-webhook/$workspaceId'
      path: '/api/public/whatsapp-webhook/$workspaceId'
      fullPath: '/api/public/whatsapp-webhook/$workspaceId'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/voice-webhook/health': {
      id: '/api/public/voice-webhook/health'
      path: '/health'
      fullPath: '/api/public/voice-webhook/health'
      preLoaderRoute: typeof ApiPublicVoiceWebhookHealthRouteImport
      parentRoute: typeof ApiPublicVoiceWebhookRoute
    }
    '/api/public/telephony/status': {
      id: '/api/public/telephony/status'
      path: '/api/public/telephony/status'
      fullPath: '/api/public/telephony/status'
      preLoaderRoute: typeof ApiPublicTelephonyStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telephony/recording': {
      id: '/api/public/telephony/recording'
      path: '/api/public/telephony/recording'
      fullPath: '/api/public/telephony/recording'
      preLoaderRoute: typeof ApiPublicTelephonyRecordingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telephony/inbound': {
      id: '/api/public/telephony/inbound'
      path: '/api/public/telephony/inbound'
      fullPath: '/api/public/telephony/inbound'
      preLoaderRoute: typeof ApiPublicTelephonyInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/retell/reschedule': {
      id: '/api/public/retell/reschedule'
      path: '/api/public/retell/reschedule'
      fullPath: '/api/public/retell/reschedule'
      preLoaderRoute: typeof ApiPublicRetellRescheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/retell/event-types': {
      id: '/api/public/retell/event-types'
      path: '/api/public/retell/event-types'
      fullPath: '/api/public/retell/event-types'
      preLoaderRoute: typeof ApiPublicRetellEventTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/retell/cancel': {
      id: '/api/public/retell/cancel'
      path: '/api/public/retell/cancel'
      fullPath: '/api/public/retell/cancel'
      preLoaderRoute: typeof ApiPublicRetellCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/retell/book': {
      id: '/api/public/retell/book'
      path: '/api/public/retell/book'
      fullPath: '/api/public/retell/book'
      preLoaderRoute: typeof ApiPublicRetellBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/retell/availability': {
      id: '/api/public/retell/availability'
      path: '/api/public/retell/availability'
      fullPath: '/api/public/retell/availability'
      preLoaderRoute: typeof ApiPublicRetellAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/retell-webhook/health': {
      id: '/api/public/retell-webhook/health'
      path: '/health'
      fullPath: '/api/public/retell-webhook/health'
      preLoaderRoute: typeof ApiPublicRetellWebhookHealthRouteImport
      parentRoute: typeof ApiPublicRetellWebhookRoute
    }
    '/api/public/retell-webhook/debug': {
      id: '/api/public/retell-webhook/debug'
      path: '/debug'
      fullPath: '/api/public/retell-webhook/debug'
      preLoaderRoute: typeof ApiPublicRetellWebhookDebugRouteImport
      parentRoute: typeof ApiPublicRetellWebhookRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hyperstream/reschedule': {
      id: '/api/public/hyperstream/reschedule'
      path: '/api/public/hyperstream/reschedule'
      fullPath: '/api/public/hyperstream/reschedule'
      preLoaderRoute: typeof ApiPublicHyperstreamRescheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hyperstream/event-types': {
      id: '/api/public/hyperstream/event-types'
      path: '/api/public/hyperstream/event-types'
      fullPath: '/api/public/hyperstream/event-types'
      preLoaderRoute: typeof ApiPublicHyperstreamEventTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hyperstream/cancel': {
      id: '/api/public/hyperstream/cancel'
      path: '/api/public/hyperstream/cancel'
      fullPath: '/api/public/hyperstream/cancel'
      preLoaderRoute: typeof ApiPublicHyperstreamCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hyperstream/book': {
      id: '/api/public/hyperstream/book'
      path: '/api/public/hyperstream/book'
      fullPath: '/api/public/hyperstream/book'
      preLoaderRoute: typeof ApiPublicHyperstreamBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hyperstream/availability': {
      id: '/api/public/hyperstream/availability'
      path: '/api/public/hyperstream/availability'
      fullPath: '/api/public/hyperstream/availability'
      preLoaderRoute: typeof ApiPublicHyperstreamAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/frejun/status': {
      id: '/api/public/frejun/status'
      path: '/api/public/frejun/status'
      fullPath: '/api/public/frejun/status'
      preLoaderRoute: typeof ApiPublicFrejunStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/frejun/flow': {
      id: '/api/public/frejun/flow'
      path: '/api/public/frejun/flow'
      fullPath: '/api/public/frejun/flow'
      preLoaderRoute: typeof ApiPublicFrejunFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calcom-webhook/$workspaceId': {
      id: '/api/public/calcom-webhook/$workspaceId'
      path: '/api/public/calcom-webhook/$workspaceId'
      fullPath: '/api/public/calcom-webhook/$workspaceId'
      preLoaderRoute: typeof ApiPublicCalcomWebhookWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agents/register': {
      id: '/api/public/agents/register'
      path: '/api/public/agents/register'
      fullPath: '/api/public/agents/register'
      preLoaderRoute: typeof ApiPublicAgentsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/agent-tools/$id': {
      id: '/api/internal/agent-tools/$id'
      path: '/api/internal/agent-tools/$id'
      fullPath: '/api/internal/agent-tools/$id'
      preLoaderRoute: typeof ApiInternalAgentToolsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime/agent/$id/export': {
      id: '/api/runtime/agent/$id/export'
      path: '/export'
      fullPath: '/api/runtime/agent/$id/export'
      preLoaderRoute: typeof ApiRuntimeAgentIdExportRouteImport
      parentRoute: typeof ApiRuntimeAgentIdRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCostEngineRoute: typeof AuthenticatedAdminCostEngineRoute
  AuthenticatedAdminUserActivityRoute: typeof AuthenticatedAdminUserActivityRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCostEngineRoute: AuthenticatedAdminCostEngineRoute,
  AuthenticatedAdminUserActivityRoute: AuthenticatedAdminUserActivityRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedBuilderRoute: typeof AuthenticatedBuilderRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCallsRoute: typeof AuthenticatedCallsRoute
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDataRoute: typeof AuthenticatedDataRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedMyAgentsRoute: typeof AuthenticatedMyAgentsRoute
  AuthenticatedPhoneNumbersRoute: typeof AuthenticatedPhoneNumbersRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedQualifiedRoute: typeof AuthenticatedQualifiedRoute
  AuthenticatedTelephonyCallsRoute: typeof AuthenticatedTelephonyCallsRoute
  AuthenticatedTelephonySettingsRoute: typeof AuthenticatedTelephonySettingsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
  AuthenticatedAgentsNewRoute: typeof AuthenticatedAgentsNewRoute
  AuthenticatedSettingsCalendarRoute: typeof AuthenticatedSettingsCalendarRoute
  AuthenticatedSettingsCrmRoute: typeof AuthenticatedSettingsCrmRoute
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedBuilderRoute: AuthenticatedBuilderRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCallsRoute: AuthenticatedCallsRoute,
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDataRoute: AuthenticatedDataRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedMyAgentsRoute: AuthenticatedMyAgentsRoute,
  AuthenticatedPhoneNumbersRoute: AuthenticatedPhoneNumbersRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedQualifiedRoute: AuthenticatedQualifiedRoute,
  AuthenticatedTelephonyCallsRoute: AuthenticatedTelephonyCallsRoute,
  AuthenticatedTelephonySettingsRoute: AuthenticatedTelephonySettingsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
  AuthenticatedAgentsNewRoute: AuthenticatedAgentsNewRoute,
  AuthenticatedSettingsCalendarRoute: AuthenticatedSettingsCalendarRoute,
  AuthenticatedSettingsCrmRoute: AuthenticatedSettingsCrmRoute,
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiPublicRetellWebhookRouteChildren {
  ApiPublicRetellWebhookDebugRoute: typeof ApiPublicRetellWebhookDebugRoute
  ApiPublicRetellWebhookHealthRoute: typeof ApiPublicRetellWebhookHealthRoute
}

const ApiPublicRetellWebhookRouteChildren: ApiPublicRetellWebhookRouteChildren =
  {
    ApiPublicRetellWebhookDebugRoute: ApiPublicRetellWebhookDebugRoute,
    ApiPublicRetellWebhookHealthRoute: ApiPublicRetellWebhookHealthRoute,
  }

const ApiPublicRetellWebhookRouteWithChildren =
  ApiPublicRetellWebhookRoute._addFileChildren(
    ApiPublicRetellWebhookRouteChildren,
  )

interface ApiPublicVoiceWebhookRouteChildren {
  ApiPublicVoiceWebhookHealthRoute: typeof ApiPublicVoiceWebhookHealthRoute
}

const ApiPublicVoiceWebhookRouteChildren: ApiPublicVoiceWebhookRouteChildren = {
  ApiPublicVoiceWebhookHealthRoute: ApiPublicVoiceWebhookHealthRoute,
}

const ApiPublicVoiceWebhookRouteWithChildren =
  ApiPublicVoiceWebhookRoute._addFileChildren(
    ApiPublicVoiceWebhookRouteChildren,
  )

interface ApiRuntimeAgentIdRouteChildren {
  ApiRuntimeAgentIdExportRoute: typeof ApiRuntimeAgentIdExportRoute
}

const ApiRuntimeAgentIdRouteChildren: ApiRuntimeAgentIdRouteChildren = {
  ApiRuntimeAgentIdExportRoute: ApiRuntimeAgentIdExportRoute,
}

const ApiRuntimeAgentIdRouteWithChildren =
  ApiRuntimeAgentIdRoute._addFileChildren(ApiRuntimeAgentIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ApiVoiceCopilotRoute: ApiVoiceCopilotRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiAdminTestRetellWebhookRoute: ApiAdminTestRetellWebhookRoute,
  ApiBuilderImportPdfRoute: ApiBuilderImportPdfRoute,
  ApiBuilderScanPdfRoute: ApiBuilderScanPdfRoute,
  ApiBuilderScriptTemplateRoute: ApiBuilderScriptTemplateRoute,
  ApiDashboardLiveCallsSseRoute: ApiDashboardLiveCallsSseRoute,
  ApiPublicApproveUserRoute: ApiPublicApproveUserRoute,
  ApiPublicElevenlabsWebhookRoute: ApiPublicElevenlabsWebhookRoute,
  ApiPublicRetellWebhookRoute: ApiPublicRetellWebhookRouteWithChildren,
  ApiPublicVoiceWebhookRoute: ApiPublicVoiceWebhookRouteWithChildren,
  ApiWebhookCustomTelemetryRoute: ApiWebhookCustomTelemetryRoute,
  ApiWebhookWatiInboundRoute: ApiWebhookWatiInboundRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiInternalAgentToolsIdRoute: ApiInternalAgentToolsIdRoute,
  ApiPublicAgentsRegisterRoute: ApiPublicAgentsRegisterRoute,
  ApiPublicCalcomWebhookWorkspaceIdRoute:
    ApiPublicCalcomWebhookWorkspaceIdRoute,
  ApiPublicFrejunFlowRoute: ApiPublicFrejunFlowRoute,
  ApiPublicFrejunStatusRoute: ApiPublicFrejunStatusRoute,
  ApiPublicHyperstreamAvailabilityRoute: ApiPublicHyperstreamAvailabilityRoute,
  ApiPublicHyperstreamBookRoute: ApiPublicHyperstreamBookRoute,
  ApiPublicHyperstreamCancelRoute: ApiPublicHyperstreamCancelRoute,
  ApiPublicHyperstreamEventTypesRoute: ApiPublicHyperstreamEventTypesRoute,
  ApiPublicHyperstreamRescheduleRoute: ApiPublicHyperstreamRescheduleRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicRetellAvailabilityRoute: ApiPublicRetellAvailabilityRoute,
  ApiPublicRetellBookRoute: ApiPublicRetellBookRoute,
  ApiPublicRetellCancelRoute: ApiPublicRetellCancelRoute,
  ApiPublicRetellEventTypesRoute: ApiPublicRetellEventTypesRoute,
  ApiPublicRetellRescheduleRoute: ApiPublicRetellRescheduleRoute,
  ApiPublicTelephonyInboundRoute: ApiPublicTelephonyInboundRoute,
  ApiPublicTelephonyRecordingRoute: ApiPublicTelephonyRecordingRoute,
  ApiPublicTelephonyStatusRoute: ApiPublicTelephonyStatusRoute,
  ApiPublicWhatsappWebhookWorkspaceIdRoute:
    ApiPublicWhatsappWebhookWorkspaceIdRoute,
  ApiRuntimeAgentIdRoute: ApiRuntimeAgentIdRouteWithChildren,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
