-- =====================================================================
-- WEBUYANYHOUSE WORKSPACE — NO CUSTOM TABLES NEEDED
-- =====================================================================
-- WeeBespoke API data is synced directly into the existing WEBEE tables:
--   • Property sellers  → public.leads        (Leads / Qualified / Pipeline pages)
--   • Buyer contacts    → public.data_records  (Contacts / Data pages)
--
-- All records are workspace-scoped (workspace_id = Webuyanyhouse workspace).
-- Row-level security on both tables already enforces isolation.
--
-- Both tables already exist — no migration SQL to apply.
-- Simply run "Activate WEBEE Workspace" + "Admin Connect" + "Sync Now"
-- from the admin panel at /admin/accounts/clients/webuyanyhouse.
-- =====================================================================

-- Optional: index for fast WBAH lead lookups (nice-to-have, not required)
-- Run this in Supabase SQL Editor if you want faster sync performance:
--
-- create index if not exists idx_leads_wbah_source
--   on public.leads (workspace_id, source_detail)
--   where source = 'import' and source_detail = 'webespoke_enterprise';
