/**
 * Conversation graph VM — types.
 *
 * The VM interprets the SAME graph Retell interprets: the `conversationFlow`
 * block produced by `src/lib/builder/export-conversation-flow.ts`. That file is
 * the semantics reference, so these types mirror its output rather than the
 * builder's internal `FlowNodeData`. Consequences worth knowing:
 *
 *   - Node discriminators are Retell's, not the builder's. The builder's 13 voice
 *     node kinds collapse into 10 flow types (`check_documents`,
 *     `send_upload_link` and `http_request` all export as `function`).
 *   - Every transition is a natural-language `transition_condition.prompt`, so
 *     routing is an LLM classification, not a boolean evaluation.
 *
 * Relative imports only — this module is reachable from vite.config.ts.
 */

// ─── Flow schema (mirrors the exported conversationFlow block) ────────────────

export interface FlowTransitionCondition {
  type: "prompt";
  prompt: string;
}

export interface FlowEdge {
  id: string;
  /** Absent on stub edges (e.g. a transfer-failed edge with nowhere to go). */
  destination_node_id?: string;
  transition_condition: FlowTransitionCondition;
}

export interface FlowInstruction {
  /** `static_text` is spoken verbatim; `prompt` is generated by the LLM. */
  type: "prompt" | "static_text";
  text: string;
}

export interface FlowGlobalNodeSetting {
  /** Natural-language condition that triggers a jump to this node. */
  condition?: string;
  /** When set, the VM returns to the pre-jump node after this one completes. */
  return_to_previous?: boolean;
  [key: string]: unknown;
}

/** Fields shared by every node type. */
export interface FlowNodeBase {
  id: string;
  name?: string;
  edges?: FlowEdge[];
  is_global?: boolean;
  global_node_setting?: FlowGlobalNodeSetting;
  model_choice?: { model?: string; [key: string]: unknown };
  instruction?: FlowInstruction;
  [key: string]: unknown;
}

export interface ConversationNode extends FlowNodeBase {
  type: "conversation";
  start_speaker?: "agent" | "user";
}

export interface FunctionNode extends FlowNodeBase {
  type: "function";
  tool_id?: string;
  tool_type?: string;
  /** Node-level webhook target for `http_request` exports. */
  url?: string;
  timeout?: number;
  description?: string;
  parameters?: Record<string, unknown>;
  speak_during_execution?: boolean;
  execution_message_description?: string;
  wait_for_result?: boolean;
  /** Followed when the tool errors. */
  else_edge?: FlowEdge;
}

export interface BranchNode extends FlowNodeBase {
  type: "branch";
  else_edge?: FlowEdge;
}

export interface ExtractVariablesNode extends FlowNodeBase {
  type: "extract_dynamic_variables";
  variables?: Array<{ name?: string; description?: string; type?: string; choices?: string[] }>;
}

export interface PressDigitNode extends FlowNodeBase {
  type: "press_digit";
  pause_detection_ms?: number;
}

export interface SmsNode extends FlowNodeBase {
  type: "sms";
  success_edge?: FlowEdge;
  failed_edge?: FlowEdge;
}

export interface CodeNode extends FlowNodeBase {
  type: "code";
  code?: string;
}

export interface TransferCallNode extends FlowNodeBase {
  type: "transfer_call";
  transfer_destination?:
    | { type: "predefined"; number?: string; extension?: string }
    | { type: "inferred"; prompt?: string }
    | Record<string, unknown>;
  transfer_option?: Record<string, unknown>;
  custom_sip_headers?: Record<string, string>;
  /** The transfer-failed fallback edge. */
  edge?: FlowEdge;
}

export interface AgentSwapNode extends FlowNodeBase {
  type: "agent_swap";
  agent_id?: string;
  agent_version?: number | string;
  edge?: FlowEdge;
}

export interface EndNode extends FlowNodeBase {
  type: "end";
}

export type FlowNode =
  | ConversationNode
  | FunctionNode
  | BranchNode
  | ExtractVariablesNode
  | PressDigitNode
  | SmsNode
  | CodeNode
  | TransferCallNode
  | AgentSwapNode
  | EndNode;

export type FlowNodeType = FlowNode["type"];

export interface ConversationFlow {
  conversation_flow_id?: string;
  global_prompt?: string;
  nodes?: FlowNode[];
  start_node_id?: string;
  start_speaker?: "agent" | "user";
  model_choice?: { model?: string; high_priority?: boolean; [key: string]: unknown };
  model_temperature?: number;
  tools?: Array<Record<string, unknown>>;
  begin_after_user_silence_ms?: number;
  [key: string]: unknown;
}

// ─── Variables ────────────────────────────────────────────────────────────────

export type VariableValue = string | number | boolean | null;

// ─── VM directives (what the VM asks the transport to do) ─────────────────────

export interface SpeakDirective {
  type: "speak";
  nodeId: string;
  text: string;
  /** True for filler speech while a tool runs, which barge-in may cut short. */
  interruptible?: boolean;
}

export interface AwaitUserDirective {
  type: "await_user";
  nodeId: string;
}

export interface AwaitDigitDirective {
  type: "await_digit";
  nodeId: string;
  pauseDetectionMs: number;
}

export interface ToolCallDirective {
  type: "tool_call";
  nodeId: string;
  toolId: string;
  result: string;
  ok: boolean;
}

export interface VariablesDirective {
  type: "variables";
  nodeId: string;
  /** Only the variables set by this step, not the whole store. */
  values: Record<string, VariableValue>;
}

export interface SmsDirective {
  type: "sms";
  nodeId: string;
  message: string;
  ok: boolean;
}

export interface TransferDirective {
  type: "transfer_call";
  nodeId: string;
  destination: string;
  /** `cold_transfer`, `warm_transfer` or `agentic_warm_transfer`. */
  transferType: string;
  sipHeaders?: Record<string, string>;
}

export interface AgentSwapDirective {
  type: "agent_swap";
  nodeId: string;
  agentId: string;
  agentVersion?: number | string;
}

export interface EndCallDirective {
  type: "end_call";
  nodeId: string;
  reason: EndReason;
}

export interface VmErrorDirective {
  type: "error";
  nodeId: string;
  message: string;
}

export type EndReason =
  | "flow_ended"
  | "transferred"
  | "agent_swapped"
  | "dead_end"
  | "step_limit"
  | "error";

export type VmDirective =
  | SpeakDirective
  | AwaitUserDirective
  | AwaitDigitDirective
  | ToolCallDirective
  | VariablesDirective
  | SmsDirective
  | TransferDirective
  | AgentSwapDirective
  | EndCallDirective
  | VmErrorDirective;

// ─── VM input ─────────────────────────────────────────────────────────────────

export type VmInput =
  | { type: "begin" }
  | { type: "user_utterance"; text: string }
  | { type: "digit"; digit: string }
  /** Host-reported outcome of a transfer, so the VM can take the failed edge. */
  | { type: "transfer_result"; ok: boolean };

// ─── Host-provided capabilities ───────────────────────────────────────────────

export interface LlmMessage {
  role: "system" | "user" | "assistant";
  content: string;
}

/**
 * The model access the VM needs. Kept narrow and injected so the VM is testable
 * without network access, and so per-node `model_choice` overrides can be
 * honoured by passing `model` through.
 */
export interface VmLlm {
  /** Free-form generation for `instruction.type === "prompt"` nodes. */
  generate(messages: LlmMessage[], options?: { model?: string }): Promise<string>;
  /**
   * Pick one of `choices` given the conversation. Must return an index into
   * `choices`, or -1 when none apply.
   */
  classify(
    messages: LlmMessage[],
    choices: string[],
    options?: { model?: string },
  ): Promise<number>;
  /** Return a JSON object for the requested fields. */
  extract(
    messages: LlmMessage[],
    fields: Array<{ name: string; description: string; type: string; choices?: string[] }>,
    options?: { model?: string },
  ): Promise<Record<string, VariableValue>>;
}

export interface ToolInvocation {
  toolId: string;
  toolName: string;
  /** `local`, `webhook`, `end_call`, … as exported by the builder. */
  toolType: string;
  url?: string;
  timeoutMs?: number;
  args: Record<string, unknown>;
  variables: Record<string, VariableValue>;
}

export interface ToolOutcome {
  ok: boolean;
  /** Serialised result injected into the transcript for downstream routing. */
  output: string;
  /** Merged into the variable store when present. */
  variables?: Record<string, VariableValue>;
  /** Set by hang-up tools (Retell's `end_call`) to stop the flow immediately. */
  endCall?: boolean;
}

/**
 * Side effects the VM delegates to its host. All optional: an unimplemented hook
 * degrades to a logged no-op that follows the failure edge rather than throwing,
 * because a caller is on the line by the time any of this runs.
 */
export interface VmHooks {
  executeTool?(invocation: ToolInvocation): Promise<ToolOutcome>;
  sendSms?(message: string, variables: Record<string, VariableValue>): Promise<boolean>;
  /**
   * Run a `code` node. Deliberately not implemented by default — evaluating
   * flow-authored JavaScript in the gateway process would be an RCE sink.
   */
  runCode?(
    code: string,
    variables: Record<string, VariableValue>,
  ): Promise<Record<string, VariableValue>>;
  log?(message: string, meta?: Record<string, unknown>): void;
}

export interface VmOptions {
  flow: ConversationFlow;
  llm: VmLlm;
  hooks?: VmHooks;
  /** Seeded dynamic variables (caller name, campaign fields, …). */
  variables?: Record<string, VariableValue>;
  /** Fallback model when the flow and node specify none. */
  model?: string;
  /**
   * Guard against flows that loop through non-blocking nodes forever
   * (branch → branch → …). Counted per turn.
   */
  maxStepsPerTurn?: number;
}
