/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedMyAgentsRouteImport } from './routes/_authenticated/my-agents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBuilderRouteImport } from './routes/_authenticated/builder'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicApproveUserRouteImport } from './routes/api/public/approve-user'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings.integrations'
import { Route as AuthenticatedSettingsCalendarRouteImport } from './routes/_authenticated/settings.calendar'
import { Route as AuthenticatedAdminUserActivityRouteImport } from './routes/_authenticated/admin.user-activity'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicRetellRescheduleRouteImport } from './routes/api/public/retell/reschedule'
import { Route as ApiPublicRetellCancelRouteImport } from './routes/api/public/retell/cancel'
import { Route as ApiPublicRetellCallAnalyzedRouteImport } from './routes/api/public/retell/call-analyzed'
import { Route as ApiPublicRetellBookRouteImport } from './routes/api/public/retell/book'
import { Route as ApiPublicRetellAvailabilityRouteImport } from './routes/api/public/retell/availability'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyAgentsRoute = AuthenticatedMyAgentsRouteImport.update({
  id: '/my-agents',
  path: '/my-agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBuilderRoute = AuthenticatedBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApproveUserRoute = ApiPublicApproveUserRouteImport.update({
  id: '/api/public/approve-user',
  path: '/api/public/approve-user',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/settings/integrations',
    path: '/settings/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsCalendarRoute =
  AuthenticatedSettingsCalendarRouteImport.update({
    id: '/settings/calendar',
    path: '/settings/calendar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUserActivityRoute =
  AuthenticatedAdminUserActivityRouteImport.update({
    id: '/admin/user-activity',
    path: '/admin/user-activity',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRetellRescheduleRoute =
  ApiPublicRetellRescheduleRouteImport.update({
    id: '/api/public/retell/reschedule',
    path: '/api/public/retell/reschedule',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRetellCancelRoute = ApiPublicRetellCancelRouteImport.update({
  id: '/api/public/retell/cancel',
  path: '/api/public/retell/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRetellCallAnalyzedRoute =
  ApiPublicRetellCallAnalyzedRouteImport.update({
    id: '/api/public/retell/call-analyzed',
    path: '/api/public/retell/call-analyzed',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRetellBookRoute = ApiPublicRetellBookRouteImport.update({
  id: '/api/public/retell/book',
  path: '/api/public/retell/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRetellAvailabilityRoute =
  ApiPublicRetellAvailabilityRouteImport.update({
    id: '/api/public/retell/availability',
    path: '/api/public/retell/availability',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/builder': typeof AuthenticatedBuilderRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-agents': typeof AuthenticatedMyAgentsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/user-activity': typeof AuthenticatedAdminUserActivityRoute
  '/settings/calendar': typeof AuthenticatedSettingsCalendarRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/api/public/approve-user': typeof ApiPublicApproveUserRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/retell/availability': typeof ApiPublicRetellAvailabilityRoute
  '/api/public/retell/book': typeof ApiPublicRetellBookRoute
  '/api/public/retell/call-analyzed': typeof ApiPublicRetellCallAnalyzedRoute
  '/api/public/retell/cancel': typeof ApiPublicRetellCancelRoute
  '/api/public/retell/reschedule': typeof ApiPublicRetellRescheduleRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/builder': typeof AuthenticatedBuilderRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-agents': typeof AuthenticatedMyAgentsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/user-activity': typeof AuthenticatedAdminUserActivityRoute
  '/settings/calendar': typeof AuthenticatedSettingsCalendarRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/api/public/approve-user': typeof ApiPublicApproveUserRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/retell/availability': typeof ApiPublicRetellAvailabilityRoute
  '/api/public/retell/book': typeof ApiPublicRetellBookRoute
  '/api/public/retell/call-analyzed': typeof ApiPublicRetellCallAnalyzedRoute
  '/api/public/retell/cancel': typeof ApiPublicRetellCancelRoute
  '/api/public/retell/reschedule': typeof ApiPublicRetellRescheduleRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/builder': typeof AuthenticatedBuilderRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/my-agents': typeof AuthenticatedMyAgentsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_authenticated/admin/user-activity': typeof AuthenticatedAdminUserActivityRoute
  '/_authenticated/settings/calendar': typeof AuthenticatedSettingsCalendarRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/api/public/approve-user': typeof ApiPublicApproveUserRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/retell/availability': typeof ApiPublicRetellAvailabilityRoute
  '/api/public/retell/book': typeof ApiPublicRetellBookRoute
  '/api/public/retell/call-analyzed': typeof ApiPublicRetellCallAnalyzedRoute
  '/api/public/retell/cancel': typeof ApiPublicRetellCancelRoute
  '/api/public/retell/reschedule': typeof ApiPublicRetellRescheduleRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pending-approval'
    | '/signup'
    | '/unsubscribe'
    | '/billing'
    | '/builder'
    | '/dashboard'
    | '/my-agents'
    | '/templates'
    | '/email/unsubscribe'
    | '/admin/user-activity'
    | '/settings/calendar'
    | '/settings/integrations'
    | '/api/public/approve-user'
    | '/lovable/email/suppression'
    | '/admin/'
    | '/api/public/payments/webhook'
    | '/api/public/retell/availability'
    | '/api/public/retell/book'
    | '/api/public/retell/call-analyzed'
    | '/api/public/retell/cancel'
    | '/api/public/retell/reschedule'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pending-approval'
    | '/signup'
    | '/unsubscribe'
    | '/billing'
    | '/builder'
    | '/dashboard'
    | '/my-agents'
    | '/templates'
    | '/email/unsubscribe'
    | '/admin/user-activity'
    | '/settings/calendar'
    | '/settings/integrations'
    | '/api/public/approve-user'
    | '/lovable/email/suppression'
    | '/admin'
    | '/api/public/payments/webhook'
    | '/api/public/retell/availability'
    | '/api/public/retell/book'
    | '/api/public/retell/call-analyzed'
    | '/api/public/retell/cancel'
    | '/api/public/retell/reschedule'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/pending-approval'
    | '/signup'
    | '/unsubscribe'
    | '/_authenticated/billing'
    | '/_authenticated/builder'
    | '/_authenticated/dashboard'
    | '/_authenticated/my-agents'
    | '/_authenticated/templates'
    | '/email/unsubscribe'
    | '/_authenticated/admin/user-activity'
    | '/_authenticated/settings/calendar'
    | '/_authenticated/settings/integrations'
    | '/api/public/approve-user'
    | '/lovable/email/suppression'
    | '/_authenticated/admin/'
    | '/api/public/payments/webhook'
    | '/api/public/retell/availability'
    | '/api/public/retell/book'
    | '/api/public/retell/call-analyzed'
    | '/api/public/retell/cancel'
    | '/api/public/retell/reschedule'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  SignupRoute: typeof SignupRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicApproveUserRoute: typeof ApiPublicApproveUserRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicRetellAvailabilityRoute: typeof ApiPublicRetellAvailabilityRoute
  ApiPublicRetellBookRoute: typeof ApiPublicRetellBookRoute
  ApiPublicRetellCallAnalyzedRoute: typeof ApiPublicRetellCallAnalyzedRoute
  ApiPublicRetellCancelRoute: typeof ApiPublicRetellCancelRoute
  ApiPublicRetellRescheduleRoute: typeof ApiPublicRetellRescheduleRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-agents': {
      id: '/_authenticated/my-agents'
      path: '/my-agents'
      fullPath: '/my-agents'
      preLoaderRoute: typeof AuthenticatedMyAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/builder': {
      id: '/_authenticated/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof AuthenticatedBuilderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/approve-user': {
      id: '/api/public/approve-user'
      path: '/api/public/approve-user'
      fullPath: '/api/public/approve-user'
      preLoaderRoute: typeof ApiPublicApproveUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/calendar': {
      id: '/_authenticated/settings/calendar'
      path: '/settings/calendar'
      fullPath: '/settings/calendar'
      preLoaderRoute: typeof AuthenticatedSettingsCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/user-activity': {
      id: '/_authenticated/admin/user-activity'
      path: '/admin/user-activity'
      fullPath: '/admin/user-activity'
      preLoaderRoute: typeof AuthenticatedAdminUserActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/retell/reschedule': {
      id: '/api/public/retell/reschedule'
      path: '/api/public/retell/reschedule'
      fullPath: '/api/public/retell/reschedule'
      preLoaderRoute: typeof ApiPublicRetellRescheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/retell/cancel': {
      id: '/api/public/retell/cancel'
      path: '/api/public/retell/cancel'
      fullPath: '/api/public/retell/cancel'
      preLoaderRoute: typeof ApiPublicRetellCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/retell/call-analyzed': {
      id: '/api/public/retell/call-analyzed'
      path: '/api/public/retell/call-analyzed'
      fullPath: '/api/public/retell/call-analyzed'
      preLoaderRoute: typeof ApiPublicRetellCallAnalyzedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/retell/book': {
      id: '/api/public/retell/book'
      path: '/api/public/retell/book'
      fullPath: '/api/public/retell/book'
      preLoaderRoute: typeof ApiPublicRetellBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/retell/availability': {
      id: '/api/public/retell/availability'
      path: '/api/public/retell/availability'
      fullPath: '/api/public/retell/availability'
      preLoaderRoute: typeof ApiPublicRetellAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedBuilderRoute: typeof AuthenticatedBuilderRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMyAgentsRoute: typeof AuthenticatedMyAgentsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedAdminUserActivityRoute: typeof AuthenticatedAdminUserActivityRoute
  AuthenticatedSettingsCalendarRoute: typeof AuthenticatedSettingsCalendarRoute
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedBuilderRoute: AuthenticatedBuilderRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMyAgentsRoute: AuthenticatedMyAgentsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedAdminUserActivityRoute: AuthenticatedAdminUserActivityRoute,
  AuthenticatedSettingsCalendarRoute: AuthenticatedSettingsCalendarRoute,
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  SignupRoute: SignupRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicApproveUserRoute: ApiPublicApproveUserRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicRetellAvailabilityRoute: ApiPublicRetellAvailabilityRoute,
  ApiPublicRetellBookRoute: ApiPublicRetellBookRoute,
  ApiPublicRetellCallAnalyzedRoute: ApiPublicRetellCallAnalyzedRoute,
  ApiPublicRetellCancelRoute: ApiPublicRetellCancelRoute,
  ApiPublicRetellRescheduleRoute: ApiPublicRetellRescheduleRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
